project:
  type: website
  output-dir: docs
  
website:
  title: "PCFG Gray Whales"
  sidebar:
    style: "docked"
    search: true
    #background: dark
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/pmahoney-noaa/noaa-pcfg-pop-ssm
          - text: Report a Bug
            href: https://github.com/pmahoney-noaa/noaa-pcfg-pop-ssm
    contents:
      - text: "Intent and summary"
        href: main/index.qmd
      - text: "Model description"
        href: main/methodology.qmd
      - text: "Model results"
        href: main/results.qmd
      #- text: "Discussion"
      #  href: main/discussion.qmd
      - section: "Supplementary"
        contents:
          - text: "Supplementary tables"
            href: main/supp_tables.qmd
          #- text: "Supplementary figures"
          #  href: main/supp_figs.qmd
          - text: "Model diagnostics"
            href: main/supp_diagnostics.qmd
      - text: "Acknowledgements"
        href: main/acknowledgement.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "2025, website authored by Peter J. Mahoney"

format:
  html:
    #theme: darkly
    linkcolor: "#007eb2"
    css: main/styles.css
    toc: true
    
execute:
  freeze: auto