---
title: "A state-space model for projecting population abundance"
---

# *Acknowledgements*

This analysis would not have been possible without the collaborating organizations and individuals contributing identification photographs. Support for the photographic identification reported here, the comparison of gray whale photographs and preparation of this report came primarily from the National Marine Fisheries Service’s West Coast Region with additional support from other collaborators. We thank Chris Yates, Lynne Barre, and Penny Ruvelas at NMFS’ West Coast Region for providing consistent funding to MML for the field surveys and photo-identification efforts. Permission to conduct some portions of this research in U.S. waters was provided by the U.S. National Marine Fisheries Service and the Makah Tribe. Portions of the research in British Columbia were conducted collaboratively with Fisheries and Oceans Canada (thanks to John Ford and Graeme Ellis). Volker Deecke assisted in analysis and matching of identifications from South Vancouver Island. William Megill coordinated providing sightings and identifications from CERF, Dawn Goley and Jeff Jacobsen coordinated effort for HSU, Christina Tombach and Dave Duffus coordinated early efforts for UVIC. Leigh Torres and her graduate students at Oregon State University (OSU) provided identification photographs from both central and southern Oregon starting in 2015 and the OSU Whale Telemetry Group provided photographs associated with their tagging efforts. Carrie Newell provided identification photographs from Depoe Bay Oregon. Merrill Gosho, Pat Gearin, Nate Pamplin, and Jonathan Scordino provided photos from Washington. Brian Gisborne’s diligence and hard work provided an immense amount of data and photographs from Vancouver Island. A number of people assisted in the field effort and in the printing and matching of photographs at Cascadia Research. Jeff Laake developed the model set and associated code. Erin Falcone, Lisa Schlender, Jennifer Quan, and Amber Klimek helped compile the data from different contributors and conducted photographic matching. Randy Lumper conducted gray whale matching in the early years of this study.
