---
title: "A state-space model for projecting population abundance"
bibliography: references.bib
---

# *Model description*

The SSM models abundance in log-space with Gaussian errors and can be defined as the following:

*Observation process:*

$$ logN_{est} \sim normal(logN, \sigma_{obs}) $$

*State process:*

$$ logN_{est_{t+1}} = logN_{est_{t}} + ln(\lambda_{t}) $$

$$ ln(\lambda_{t}) \sim normal(\mu, \sigma) $$

Where $logN$ and $\sigma_{obs}$ are the estimated (log) population abundance and standard error for each year with observation data, respectively. Models vary by the specification of $\lambda$ - or the intrinsic rate of growth in a population from year to year - and the factors hypothesized to be correlated with population growth, at least given current knowledge and available data within this system. At present, six models were considered.

1.  Base: assumes future PCFG whale abundance is informed by an average growth rate ($\mu_{ln(\lambda)}$), with an associated measure of variability or uncertainty ($\sigma_{ln(\lambda)}$), for all years since 2002.

    $$ \mu = \mu_{ln(\lambda)}; \sigma = \sigma_{ln(\lambda)} $$

3.  AR1: assumes an autoregressive correlation in population growth ($\lambda$). In this case, population growth in the current year ($\mu$ or $ln(\lambda_{t})$) is dependent upon population growth in the previous year ($ln(\lambda_{t-1})$), permitting more persistent trends in population abundance through time.

    $$ \mu = ln(\lambda_{t-1}); \sigma = \sigma_{ln(\lambda)} $$

4.  ENP calves: similar to the Base model, the ENP calves model includes a covariate representing the number of Eastern North Pacific (ENP) gray whale calves, permitting our average expectation for population growth to scale ($\beta_{calves}$) with the number of reported calves in the previous year ($C_{t-1}$). The ENP calves model is informed by a long-term dataset from counts of gray whale calves as they migrate with their mothers past Piedras Blancas, California to more northerly feeding grounds in the Bering, Beaufort, and Chukchi seas [@lang2024]. Notably, the numbers of ENP calves correlates with calf numbers observed in the PCFG range, providing the benefit of standardized and rigorous time series than for PCFG calves alone. Further, these data are more consistently available during years in which PCFG abundance estimates, or possibly PCFG calf counts, are available, providing a measure of constraint on our expectations for population growth during projected years.

    $$ \mu = \mu_{ln(\lambda)} + \beta_{calves} * C_{t-1}; \sigma = \sigma_{ln(\lambda)} $$

5.  PCFG Calves only: as with the ENP calves model, the PCFG calves model includes a covariate representing the number of PCFG gray whale calves, permitting our average expectation for population growth to scale ($\beta_{calves}$) with the number of reported calves in the previous year ($C_{t-1}$). PCFG calf counts are collected during the feeding season (June-November) surveys in the PCFG range of 41°-52°N. Observed whales can be hard to classify as calves during the feeding season because the mean observed weaning date is 1 August, after which observers cannot confidently classify the whale as a calf [@calambokidis2017]. The advantage of this data set is that it is a direct observation of just PCFG whales and is not influenced by fluctuations in productivity of ENP whales that feed in the Arctic.

    $$ \mu = \mu_{ln(\lambda)} + \beta_{calves} * C_{t-1}; \sigma = \sigma_{ln(\lambda)} $$

6.  ENP Strandings only: includes a covariate representing the number of gray whale strandings along the coasts of California, Oregon, and Washington, permitting our average expectation for population growth to scale ($\beta_{strand}$) with the number of reported strandings (ENP, including PCFG) in the previous year ($S_{t-1}$) during primarily the northbound migration.nDuring stranding events, it is very rare to be able to determine if a whale is a PCFG whale or not often due to the body position of the whale on the beach and decomposition. Stranding data is routinely collected and will often be available in the years in which PCFG abundance is forecasted. 

    $$ \mu = \mu_{ln(\lambda)} + \beta_{strand} * S_{t-1}; \sigma = \sigma_{ln(\lambda)} $$

7.  PCFG Calves + ENP Strandings: incorporates both strandings and PCFG calf production as covariates informing the estimates of population growth. @stewart2023 documented that calf production and stranding records were important variables for estimating the abundance of ENP gray whales, particularly for years when no abundance estimates were collected.

    $$ \mu = \mu_{ln(\lambda)} + \beta_{calves} * C_{t-1} + \beta_{strand} * S_{t-1}; \sigma = \sigma_{ln(\lambda)} $$

<!--#  1. Base: $ln(\lambda_{t}) \sim normal(\mu_{ln(\lambda)}, \sigma_{ln(\lambda)})$  2. AR1v1: $ln(\lambda_{t}) \sim normal(ln(\lambda_{t-1}), \sigma_{ln(\lambda_{t})})$  3. AR2v2: $ln(\lambda_{t}) \sim normal(\mu_{ln(\lambda_{t})} + ln(\lambda_{t-1}) * \beta, \sigma_{ln(\lambda_{t})})$  4. ENP calves: $ln(\lambda_{t}) \sim normal(\mu_{ln(\lambda_{t})} + C_{t} * \beta_{calves}, \sigma_{ln(\lambda_{t})})$  5. (PCFG) Calves only: $ln(\lambda_{t}) \sim normal(\mu_{ln(\lambda_{t})} + C_{t} * \beta_{calves}, \sigma_{ln(\lambda_{t})})$  6. (ENP) Strandings only: $ln(\lambda_{t}) \sim normal(\mu_{ln\lambda} + S_{t} * \beta_{strand}, \sigma_{ln\lambda})$  7. (PCFG) Calves + Strandings: $ln(\lambda_{t}) \sim normal(\mu_{ln(\lambda_{t})} + C_{t} * \beta_{calves} + S_{t} * \beta_{strand}, \sigma_{ln(\lambda_{t})})$  -->

### Additional prior specifications

Where appropriate, the following weakly informative hyper-priors were implemented for both mean and scale parameters in the $ln(\lambda)$ priors.

$$ \mu_{ln(\lambda)} \sim normal(0, 1) $$

$$ \sigma_{ln(\lambda)} \sim lognormal(0, 1) $$

Importantly, $\sigma_{ln(\lambda_{t})}$ is constrained to be positive. For models with beta coefficients (models 4 - 6), additional normal priors are specified for each coefficient, *i* (e.g., $ln(\lambda_{t-1})$, ENP calves, PCFG calves, or number of strandings). At present, no hyper-priors were used for coefficients.

$$ \beta_i \sim normal(0, 1) $$

# 

# *Modeling environment*

All modeling was conducted using the package `cmdstanr` [@cmdstanr] in **R** [@Rcore] . Posterior sampling was performed using Hamiltonian Monte Carlo with three chains in parallel. The number of warmup (n~i~ = 1000) and sampling iterations (n~i~ = 1000) were kept at their defaults as these were adequate for sampling posterior distributions. Refer to the chain diagnostic summary [table](supp_diagnostics.html) or the [R code](https://github.com/pmahoney-noaa/noaa-pcfg-pop-ssm) for more details.
